# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\LapTrinhPython\WorkNote\Views\main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1318, 760)
        MainWindow.setStyleSheet("*{\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    font-family: \'Segoe UI\';\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-color: #f2f2f2;\n"
"}\n"
"\n"
"#search_inp {\n"
"    padding: 0 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#search_btn {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"    background-color: rgba(236, 236, 236, 1);\n"
"}\n"
"\n"
".QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#LeftMenuContainer .QPushButton{\n"
"    text-align: left;\n"
"    padding: 2px 8px;\n"
"}\n"
"\n"
"#bodyContainer {\n"
"    \n"
"    background-color: rgb(54, 142, 104);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyArea = QtWidgets.QWidget(self.centralwidget)
        self.BodyArea.setObjectName("BodyArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BodyArea)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftMenuContainer = QtWidgets.QWidget(self.BodyArea)
        self.LeftMenuContainer.setMinimumSize(QtCore.QSize(250, 0))
        self.LeftMenuContainer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.LeftMenuContainer.setObjectName("LeftMenuContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LeftMenuContainer)
        self.verticalLayout_3.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.LeftMenuContainer)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.LeftMenuContainer)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeTable_btn = QtWidgets.QPushButton(self.frame_2)
        self.timeTable_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.timeTable_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.timeTable_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/Timetable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timeTable_btn.setIcon(icon)
        self.timeTable_btn.setIconSize(QtCore.QSize(24, 24))
        self.timeTable_btn.setObjectName("timeTable_btn")
        self.verticalLayout_2.addWidget(self.timeTable_btn)
        self.ntuCourses_btn = QtWidgets.QPushButton(self.frame_2)
        self.ntuCourses_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.ntuCourses_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.ntuCourses_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/icons/Book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ntuCourses_btn.setIcon(icon1)
        self.ntuCourses_btn.setIconSize(QtCore.QSize(24, 24))
        self.ntuCourses_btn.setObjectName("ntuCourses_btn")
        self.verticalLayout_2.addWidget(self.ntuCourses_btn)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.LeftMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(self.BodyArea)
        self.mainBodyContainer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainBodyContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bodyContainer = QtWidgets.QStackedWidget(self.mainBodyContainer)
        self.bodyContainer.setObjectName("bodyContainer")
        self.horizontalLayout_2.addWidget(self.bodyContainer)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        self.verticalLayout.addWidget(self.BodyArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeTable_btn.setText(_translate("MainWindow", "Thời khoá biểu"))
        self.ntuCourses_btn.setText(_translate("MainWindow", "Học phần"))
from Views import resources_rc
