# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\LapTrinhPython\WorkNote\Views\nc_entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ntu_entry(object):
    def setupUi(self, ntu_entry):
        ntu_entry.setObjectName("ntu_entry")
        ntu_entry.resize(658, 61)
        ntu_entry.setMinimumSize(QtCore.QSize(500, 60))
        ntu_entry.setMaximumSize(QtCore.QSize(16777215, 80))
        ntu_entry.setStyleSheet("\n"
"#mainBodyContainer {\n"
"    border-radius: 6px;\n"
"    background-color: #f6f6f6;\n"
"}\n"
"\n"
"#mainBodyContainer:hover {\n"
"    background-color: #fdfdfd;\n"
"}")
        self.ntu_entry_lo = QtWidgets.QHBoxLayout(ntu_entry)
        self.ntu_entry_lo.setContentsMargins(0, 0, 0, 0)
        self.ntu_entry_lo.setSpacing(0)
        self.ntu_entry_lo.setObjectName("ntu_entry_lo")
        self.mainBodyContainer = QtWidgets.QWidget(ntu_entry)
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainBodyContainer)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.courseName_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.courseName_lb.setMinimumSize(QtCore.QSize(200, 0))
        self.courseName_lb.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.courseName_lb.setFont(font)
        self.courseName_lb.setText("")
        self.courseName_lb.setWordWrap(True)
        self.courseName_lb.setObjectName("courseName_lb")
        self.horizontalLayout.addWidget(self.courseName_lb)
        self.year_lb = QtWidgets.QLabel(self.mainBodyContainer)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.year_lb.setFont(font)
        self.year_lb.setText("")
        self.year_lb.setObjectName("year_lb")
        self.horizontalLayout.addWidget(self.year_lb)
        self.semester_lb = QtWidgets.QLabel(self.mainBodyContainer)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.semester_lb.setFont(font)
        self.semester_lb.setText("")
        self.semester_lb.setObjectName("semester_lb")
        self.horizontalLayout.addWidget(self.semester_lb)
        self.ntu_entry_lo.addWidget(self.mainBodyContainer)

        self.retranslateUi(ntu_entry)
        QtCore.QMetaObject.connectSlotsByName(ntu_entry)

    def retranslateUi(self, ntu_entry):
        _translate = QtCore.QCoreApplication.translate
        ntu_entry.setWindowTitle(_translate("ntu_entry", "Form"))
