# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Workspace\NTU_project\LapTrinhPython\WorkNote\Views\tb_entries.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tbEtriesForm(object):
    def setupUi(self, tbEtriesForm):
        tbEtriesForm.setObjectName("tbEtriesForm")
        tbEtriesForm.resize(639, 60)
        tbEtriesForm.setMinimumSize(QtCore.QSize(632, 60))
        tbEtriesForm.setMaximumSize(QtCore.QSize(16777215, 80))
        tbEtriesForm.setStyleSheet("\n"
"#mainBodyContainer {\n"
"    margin-top: 6px;\n"
"    border-radius: 6px;\n"
"    background-color: #f6f6f6;\n"
"\n"
"}\n"
"\n"
"#mainBodyContainer:hover {\n"
"    \n"
"    background-color: #fcfcfc;\n"
"}\n"
"\n"
".QLabel {\n"
"    padding: 8px 2px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(tbEtriesForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainBodyContainer = QtWidgets.QWidget(tbEtriesForm)
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainBodyContainer)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.name_lb.setMinimumSize(QtCore.QSize(200, 0))
        self.name_lb.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_lb.setFont(font)
        self.name_lb.setText("")
        self.name_lb.setWordWrap(True)
        self.name_lb.setObjectName("name_lb")
        self.horizontalLayout_2.addWidget(self.name_lb)
        self.day_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.day_lb.setMinimumSize(QtCore.QSize(60, 0))
        self.day_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day_lb.setFont(font)
        self.day_lb.setText("")
        self.day_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.day_lb.setObjectName("day_lb")
        self.horizontalLayout_2.addWidget(self.day_lb)
        self.room_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.room_lb.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_lb.setFont(font)
        self.room_lb.setText("")
        self.room_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.room_lb.setObjectName("room_lb")
        self.horizontalLayout_2.addWidget(self.room_lb)
        self.lesson_lb = QtWidgets.QLabel(self.mainBodyContainer)
        self.lesson_lb.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lesson_lb.setFont(font)
        self.lesson_lb.setText("")
        self.lesson_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lesson_lb.setObjectName("lesson_lb")
        self.horizontalLayout_2.addWidget(self.lesson_lb)
        self.horizontalLayout.addWidget(self.mainBodyContainer)

        self.retranslateUi(tbEtriesForm)
        QtCore.QMetaObject.connectSlotsByName(tbEtriesForm)

    def retranslateUi(self, tbEtriesForm):
        _translate = QtCore.QCoreApplication.translate
        tbEtriesForm.setWindowTitle(_translate("tbEtriesForm", "Form"))
